// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFINLbi3isX703H20NFIjIohCXozIunUU',
    appId: '1:506781937368:android:25194ab45069eec2deb1ad',
    messagingSenderId: '506781937368',
    projectId: 'dailywatertracker-app-prod',
    storageBucket: 'dailywatertracker-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Mxvg25pL7BSyTH-BodkrTeaqm_-o_Ck',
    appId: '1:506781937368:ios:c139bdcf76bd5775deb1ad',
    messagingSenderId: '506781937368',
    projectId: 'dailywatertracker-app-prod',
    storageBucket: 'dailywatertracker-app-prod.firebasestorage.app',
    androidClientId: '506781937368-js014ai30sqq1r2ej8a9ri6gjc8pcpu8.apps.googleusercontent.com',
    iosClientId: '506781937368-m4q7n7u4l92di5ru78qcgtq6125b961f.apps.googleusercontent.com',
    iosBundleId: 'com.dailywatertracker.app.prod',
  );

}