// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrKegZ_sU5hAvPzCjuDU5MUmGaU7-wc0',
    appId: '1:194002919052:android:938db489b5bbf5cf3465a9',
    messagingSenderId: '194002919052',
    projectId: 'dailywatertracker-app-dev',
    storageBucket: 'dailywatertracker-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-BrfL-qjg0DETCDDB-x_g2rfUxWGRbSk',
    appId: '1:194002919052:ios:4de54fe98b8536c93465a9',
    messagingSenderId: '194002919052',
    projectId: 'dailywatertracker-app-dev',
    storageBucket: 'dailywatertracker-app-dev.firebasestorage.app',
    androidClientId: '194002919052-fjvsvgjo58su9sktedgqblkmj6gknqfa.apps.googleusercontent.com',
    iosClientId: '194002919052-ocjnabf7vhek7f2n18g15vhi1s5psrlm.apps.googleusercontent.com',
    iosBundleId: 'com.dailywatertracker.app.dev',
  );

}